apiVersion: apps/v1
kind: Deployment
namespace: {{ .Release.Namespace | quote }}
metadata:
  name: {{ include "rtdb.vzdb.fullname" . }}
  labels:
    app:
{{ include "rtdb.vzdb.labels" . | indent 4 }}   
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "rtdb.vzdb.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "rtdb.vzdb.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.rtdb.vzdb.image }}:{{ .Values.rtdb.vzdb.imageTag }}"
        name: {{ .Chart.Name }}
        ports:
        - name: kdm-rtdb-port
          containerPort: {{ .Values.service.internalPort }}
        env:
        - name: kdm.rtdb.host
          value: "hoosst"
        - name: kdm.rtdb.port
          value: {{ .Values.env.port }}
        - name: kdm.rtdb.password
          value: {{ .Values.env.password }}
        - name: kdm.rtdb.username
          value: {{ .Values.env.username }}
        - name: kdm.rtdb.rule
          value: {{ .Values.env.rule }}
        resources: {}
        volumeMounts:
          - mountPath: /etc/localtime:ro
            name: rtdb-vzdb-localtime
          - mountPath: /oge/log
            name: rtdb-vzdb-log
      restartPolicy: Always
      volumes:
      - name: rtdb-vzdb-localtime
        hostPath:
          path: /etc/localtime
      - name: rtdb-vzdb-log
        hostPath:
          path: /home/oge/oge_logs/kdm-rdp-rtdb-vzdb-{{ .Values.service.externalPort}}/