apiVersion: v1
kind: Service
metadata:
  labels:
    app: kdm-rtdb
  name: kdm-rtdb
spec:
  type: NodePort
  ports:
  - name: kdm-rtdb-port
    port: 8040
    targetPort: 8040
    nodePort: 8040
  selector:
    app: kdm-rtdb
status:
  loadBalancer: {}
