apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "kdm.rdp.rtdb.vzdb.name" . }}
  name: {{ include "kdm.rdp.rtdb.vzdb.name" . }}
spec:
  type: NodePort
  ports:
  - name: kdm-rtdb-port
    port: 8040
    targetPort: 8040
    nodePort: 8040
  selector:
    app: {{ include "kdm.rdp.rtdb.vzdb.name" . }}
status:
  loadBalancer: {}
