apiVersion: apps/v1
kind: Deployment
namespace: {{ .Release.Namespace | quote }}
metadata:
  name: {{ include "vzdb.fullname" . }}
  labels:
{{ include "vzdb.labels" . | indent 4 }}   
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "vzdb.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "vzdb.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.vzdb.image }}:{{ .Values.vzdb.imageTag }}"
        # name: {{ .Values.vzdb.containerName }}
        name: {{ .Chart.Name }}
        ports:
        - name: kdm-vzdb-port
          containerPort: {{ .Values.service.vzdb.internalPort}}
        - containerPort: {{ .Values.service.vzevt.internalPort}}
        resources: {}
        volumeMounts:
          - mountPath: /etc/localtime:ro
            name: vzdb-localtime
          - mountPath: /oge/vzdb/model
            name: vzdb-model
          - mountPath: /oge/vzdb/cache
            name: vzdb-cache
          - mountPath: /oge/vzdb/data
            name: vzdb-data
          - mountPath: /oge/vzdb/log
            name: vzdb-log
      restartPolicy: Always
      volumes:
      - name: vzdb-localtime
        hostPath:
          path: /etc/localtime
      - name: vzdb-model
        hostPath:
          path: /home/oge/oge_data/vzdb-{{ .Values.service.vzdb.externalPort}}/model/
      - name: vzdb-cache
        hostPath:
          path: /home/oge/oge_data/vzdb-{{ .Values.service.vzdb.externalPort}}/cache/
      - name: vzdb-data
        hostPath:
          path: /home/oge/oge_data/vzdb-{{ .Values.service.vzdb.externalPort}}/data/
      - name: vzdb-log
        hostPath:
          path: /home/oge/oge_logs/vzdb-volume-{{ .Values.service.vzdb.externalPort}}/
