apiVersion: v1
kind: Service
namespace: {{ .Release.Namespace | quote }}
metadata:
  labels:
{{ include "vzdb.labels" . | indent 4 }}
  name: {{ include "vzdb.fullname" . }}
spec:
  type: {{ .Values.service.vzdb.type }}
  ports:
  - name: kdm-vzdb-port
    port: {{ .Values.service.vzdb.internalPort }}
    targetPort: kdm-vzdb-port
    nodePort: {{ .Values.service.vzdb.externalPort }}
  selector:
    app: {{ include "vzdb.fullname" . }}
    release: {{ .Release.Name }}
status:
  loadBalancer: {}
