apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "vzdb.labels" . | indent 4 }}
  name: {{ .Values.vzdb.containerName }}
spec:
  type: {{ .Values.service.vzdb.type }}
  ports:
  - name: kdm-vzdb-port
    port: {{ .Values.service.vzdb.internalPort }}
    targetPort: kdm-vzdb-port
    nodePort: {{ .Values.service.vzdb.externalPort }}
  selector:
    app.kubernetes.io/name: {{ include "vzdb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    namespace: {{ .Release.Namespace }}
status:
  loadBalancer: {}
