apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "vzdb.name" . }}
  name: {{ .Values.vzdb.containerName }}
spec:
  type: {{ .Values.service.vzdb.type }}
  ports:
  - name: kdm-vzdb-port
    port: {{ .Values.service.vzdb.internalPort }}
    targetPort: kdm-vzdb-port
    nodePort: {{ .Values.service.vzdb.externalPort }}
  selector:
    app: {{ include "vzdb.name" . }}
status:
  loadBalancer: {}
