apiVersion: apps/v1
kind: Deployment
metadata:
  name: vzdb
  labels:
    app: vzdb
spec:
  replicas: 1
  selector:
    matchLabels:
        app: vzdb
  template:
    metadata:
      labels:
        app: vzdb
    spec:
      containers:
      - image: docker.orientge.cn:5000/oge/vzdb:2.72.1
        name: vzdb-vvv
        ports:
        - containerPort: 22235
        - containerPort: 22136
        resources: {}
        volumeMounts:
          - mountPath: /etc/localtime:ro
            name: vzdb-localtime
          - mountPath: /oge/vzdb/model
            name: vzdb-model
          - mountPath: /oge/vzdb/cache
            name: vzdb-cache
          - mountPath: /oge/vzdb/data
            name: vzdb-data
          - mountPath: /oge/vzdb/log
            name: vzdb-log
      restartPolicy: Always
      volumes:
      - name: vzdb-localtime
        hostPath:
          path: /etc/localtime
      - name: vzdb-model
        hostPath:
          path: /home/oge/oge_data/vzdb-volume-{{ .Values.service.vzdb.nodePort}}/model/
      - name: vzdb-cache
        hostPath:
          path: /home/oge/oge_data/vzdb-volume-{{ .Values.service.vzdb.nodePort}}/cache/
      - name: vzdb-data
        hostPath:
          path: /home/oge/oge_data/vzdb-volume-{{ .Values.service.vzdb.nodePort}}/data/
      - name: vzdb-log
        hostPath:
          path: /home/oge/oge_logs/vzdb-volume-{{ .Values.service.vzdb.nodePort}}
