apiVersion: v1
kind: Service
# metadata:
#   labels:
#     io.kompose.service: vzdb
#   name: vzdb
spec:
  ports:
  - name: "32235"
    port: 32235
    targetPort: 22235
  - name: "32136"
    port: 32136
    targetPort: 22136
  selector:
    app: vzdb
status:
  loadBalancer: {}
