apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
  labels:
    app: consul
spec:
  replicas: 1
  selector:
    matchLabels:
        app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - image: "{{ .Values.consul.image }}:{{ .Values.consul.imageTag }}"
        name: consul
        ports:
        - containerPort: 8500
        - containerPort: 8600
        - containerPort: 8300
        resources: {}
      restartPolicy: Always
      env:
      - name: CONSUL_LOCAL_CONFIG
        value: {{ .Values.local.config  | quote}}