apiVersion: v1
kind: Service
metadata:
  labels:
    app: consul
  name: consul
spec:
  type: {{ .Values.service.type}}
  ports:
  - port: 8500
    targetPort: 8500
  selector:
    app: consul
status:
  loadBalancer: {}
