apiVersion: v1
kind: Service
metadata:
  labels:
    app: consul
  name: consul
spec:
  # type: {{ .Values.service.type}}
  clusterIP: None
  ports:
  - port: 8500
    targetPort: 8500
    # nodePort: 8500
    name: ui
  selector:
    app: consul
status:
  loadBalancer: {}
