apiVersion: apps/v1
kind: Deployment
namespace: {{ .Release.Namespace | quote }}
metadata:
  name: {{ include "consul.fullname" . }}
  labels:
{{ include "consul.labels" . | indent 4 }}   
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "consul.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "consul.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.consul.image }}:{{ .Values.consul.imageTag }}"
        name: consul
        ports:
        - name: ui-port
          containerPort: {{ .Values.service.internalPort}}
        - containerPort: 8600
        - containerPort: 8300
        resources: {}
      restartPolicy: Always
      env:
      - name: CONSUL_LOCAL_CONFIG
        value: {{ .Values.local.config  | quote}}