apiVersion: v1
kind: Service
namespace: {{ .Release.Namespace | quote }}
metadata:
  labels:
{{ include "consul.labels" . | indent 4 }}
  name: {{ include "consul.fullname" . }}
spec:
  type: {{ .Values.service.type}}
  ports:
  - port: {{ .Values.service.internalPort}}
    targetPort: ui-port
    nodePort: {{ .Values.service.internalPort}}
    name: ui-port
  selector:
    app: {{ include "consul.fullname" . }}
    release: {{ .Release.Name }}
status:
  loadBalancer: {}
