apiVersion: apps/v1
kind: Deployment
namespace: {{ .Release.Namespace | quote }}
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
{{ include "postgres.labels" . | indent 4 }}   
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "postgres.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "postgres.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.postgres.image }}:{{ .Values.postgres.imageTag }}"
        name: {{ .Chart.Name }}
        ports:
        - name: postgres-port
          containerPort: {{ .Values.service.internalPort}}
        env:
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.env.password | quote }}
        - name: POSTGRES_DB
          value: {{ .Values.postgres.env.db | quote }}
        resources: {}
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-data
          - mountPath: /docker-entrypoint-initdb.d
            name: postgres-init
          - mountPath: /backup
            name: postgres-backup
          - mountPath: /etc/localtime:ro
            name: postgres-localtime
      restartPolicy: Always
      volumes:
      - name: postgres-localtime
        hostPath:
          path: /etc/localtime
      - name: postgres-data
        hostPath:
          path: /home/oge/oge_data/postgres-{{ .Values.service.externalPort}}/data/
      - name: postgres-init
        hostPath:
          path: /home/oge/oge_data/postgres-{{ .Values.service.externalPort}}/init/
      - name: postgres-backup
        hostPath:
          path: /home/oge/oge_data/postgres-{{ .Values.service.externalPort}}/backup/
