apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  type: {{ .Values.service.postgres.type }}
  ports:
  - name: postgres-port
    port: 5432
    targetPort: postgres-port
    nodePort: {{ .Values.service.postgres.nodePort }}
  selector:
    app: postgres
status:
  loadBalancer: {}
