apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kdm-rdp
  name: kdm-rdp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kdm-rdp
  template:
    metadata:
      labels:
        app: kdm-rdp
    spec:
      containers:
      {{- with .Values.rdp.env }}
      - env:
        - name: spring.profiles.active
          value: reg_consul,alias_none
        - name: kdm.reg.host
          value: {{ .Values.rdp.env.reg.host}}
        - name: jdbc.database
          value: {{ .database | quote }}
        - name: jdbc.password
          value: {{ .password | quote }}
        - name: jdbc.port
          value: {{ .port | quote }}
        - name: jdbc.username
          value: {{ .username | quote }}
        {{- end }}
        image: "{{ .Values.rdp.image }}:{{ .Values.rdp.imageTag }}"
        name: kdm-rdp-8082
        ports:
        - containerPort: 8082
        resources: {}
        volumeMounts:
          - mountPath: /etc/localtime:ro
            name: rdp-localtime
          - mountPath: /oge/log
            name: rdp-log
      restartPolicy: Always
      volumes:
      - name: rdp-localtime
        hostPath:
          path: /etc/localtime
      - name: rdp-log
        hostPath:
          path: /home/oge/oge_logs/kdm-rdp-8082
status: {}
