apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kdm-rdp
  name: kdm-rdp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kdm-rdp
  template:
    metadata:
      labels:
        app: kdm-rdp
    spec:
      containers:
      {{- with .Values.rdp.env }}
      - env:
        - name: jdbc.database
          value: {{ .database | quote }}
        - name: jdbc.password
          value: {{ .password | quote }}
        - name: jdbc.port
          value: {{ .port | quote }}
        - name: jdbc.username
          value: {{ .username | quote }}
        {{- end }}
        image: "{{ .Values.rdp.image }}:{{ .Values.rdp.imageTag }}"
        name: kdm-rdp-8082
        ports:
        - containerPort: 8082
        resources: {}
      restartPolicy: Always
status: {}
