apiVersion: v1
kind: Service
namespace: {{ .Release.Namespace | quote }}
metadata:
  labels:
{{ include "rdp.labels" . | indent 4 }}   
  name: {{ include "rdp.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: kdm-rdp-port
    port: {{ .Values.service.externalPort }}
    targetPort: kdm-rdp-port
    nodePort: {{ .Values.service.externalPort }}
  selector:
    app: {{ include "rdp.fullname" . }}
    release: {{ .Release.Name }}
status:
  loadBalancer: {}
